// <auto-generated />
namespace QLBH.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class dropcolumnstatusinbilltable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(dropcolumnstatusinbilltable));
        
        string IMigrationMetadata.Id
        {
            get { return "202007261158169_drop-column-status-in-bill-table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
